#! /bin/sh

# Uncomment for debugging purpose. Regular admins are not allowed to write to
# /dev/console.
# exec 2>/dev/console

. /usr/html/axis-cgi/lib/functions.sh

PART=
RELEASE=

[ -f /usr/share/axis-release/variables ] && . /usr/share/axis-release/variables

version=${RELEASE:-unknown}

[ "$PART" ] || {
	[ -f /usr/share/axis-release/part ] && . /usr/share/axis-release/part
	[ "$PART" ] || PART=unknown
}

__cgi_hdgen yes
cat <<-EOF
	part: $PART
	version: $version
EOF

exit 0
